Repository L3v3L/salto-game, pull requests merged in 2019-11, with the labels that each got.

#18 feature/redux
  package-lock.json
  package.json
  public/manifest.json
  src/App.css
  src/App.js
  src/components/Battle.js
  src/components/Card.js
  src/components/Monster.js
  src/components/Sprites.js
  src/index.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/index.js
  src/redux/reducers/monsters.js
  src/redux/selectors.js
  src/redux/store.js
Labels: enhancement

#23 feature/migrate state to redux store
  src/components/Battle.js
  src/components/Card.js
  src/components/Monster.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/cards.js
  src/redux/reducers/index.js
  src/redux/reducers/player.js
  src/redux/selectors.js
Labels: enhancement

#24 Card Styling
  src/components/Battle.js
  src/components/Card.js
  src/redux/actions.js
  src/redux/reducers/cards.js
Labels: enhancement

#35 Uses unique card id as the key of Card instances
  src/components/Battle.js
Labels: bug

#34 Prevents card text selection using user-select property
  src/components/Card.js
Labels: enhancement

#36 feature/reducks
  src/components/Battle.js
  src/components/Card.js
  src/configureStore.js
  src/ducks/battle.js
  src/ducks/cards.js
  src/ducks/index.js
  src/ducks/monsters.js
  src/ducks/player.js
  src/index.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/cards.js
  src/redux/reducers/index.js
  src/redux/reducers/monsters.js
  src/redux/reducers/player.js
  src/redux/selectors.js
  src/redux/store.js
Labels: enhancement

#37 Fuses battle, cards, monsters and player ducks into a game duck
  src/components/Battle.js
  src/components/Card.js
  src/components/Monster.js
  src/configureStore.js
  src/ducks/battle.js
  src/ducks/cards.js
  src/ducks/game.js
  src/ducks/index.js
  src/ducks/monsters.js
  src/ducks/player.js
  src/index.js
Labels: enhancement

#39 Feature/game
  src/App.js
  src/components/Battle.js
  src/components/Card.js
  src/components/CardLibrary.js
  src/components/Game.js
  src/configureStore.js
  src/ducks/game.js
Labels: enhancement

#44 Feature/endturn
  src/components/Battle.js
  src/ducks/game.js
Labels: enhancement

#49 Implements targeted attack
  src/components/Battle.js
  src/components/Card.js
  src/components/CardLibrary.js
  src/components/Monster.js
  src/ducks/game.js
Labels: enhancement

#62 Refactors ducks
  src/components/Battle.js
  src/components/Card.js
  src/components/Game.js
  src/components/Monster.js
  src/configureStore.js
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/game.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
  src/ducks/selectors.js
  src/index.js
Labels: enhancement

#67 Refact/move endturn logic
  src/components/Battle.js
  src/components/Card.js
  src/configureStore.js
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
Labels: enhancement

#69 Implements targeting and attacking functionality using middlewares
  src/components/Battle.js
  src/components/Card.js
  src/components/CardLibrary.js
  src/components/Monster.js
  src/configureStore.js
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
  src/ducks/selectors.js
Labels: enhancement

#72 Refactors active card
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
  src/ducks/selectors.js
Labels: enhancement

#77 Attack all
  src/components/Card.js
  src/components/CardLibrary.js
  src/configureStore.js
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
Labels: enhancement

#82 Deactivate cards after use and when ending turn
  src/ducks/middlewares.js
Labels: bug

#94 show queued moves for every monster
  src/components/Battle.js
  src/components/Monster.js
Labels: enhancement

#104 show turn count, closes #95
  src/components/Battle.js
Labels: enhancement

#102 player hp bar (closes #28)
  src/components/Battle.js
  src/components/PlayerHP.js
Labels: enhancement

#98 Shield and Weaken cards
  src/components/Battle.js
  src/components/CardLibrary.js
  src/components/Game.js
  src/components/Monster.js
  src/configureStore.js
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
  src/ducks/selectors.js
Labels: enhancement

#106 Visual overhaul
  src/App.css
  src/App.js
  src/components/Battle.js
  src/components/Card.js
  src/components/DeckPile.js
  src/components/DiscardPile.js
  src/components/Game.js
  src/components/Monster.js
  src/components/MonsterLibrary.js
  src/components/PercentileBar.js
  src/components/PlayerHP.js
  src/components/styles/BattleStyle.js
  src/ducks/selectors.js
Labels: enhancement

#111 Styles the battle screen and end turn button, closes #65
  src/components/styles/BattleStyle.js
Labels: enhancement

#112 Create deployment workflow
  .github/workflows/main.yml
  package-lock.json
  package.json
  scripts/deploy.js
Labels: enhancement

#113 Adds page title
  public/index.html
Labels: enhancement

#180 Adds demo page link to README.md
  README.md
Labels: documentation

#187 Allows configuration of the card destination after being played
  src/ducks/actionCreators.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
Labels: enhancement

#189 Feature/card14
  public/images/14.svg
  public/images/21.svg
  public/images/37.svg
  src/components/CardLibrary.js
  src/components/Game.js
  src/ducks/actionCreators.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
Labels: enhancement

#191 Adds reward screen functionality
  src/components/CardLibrary.js
  src/components/Game.js
  src/components/RewardScreen.js
  src/ducks/actionCreators.js
  src/ducks/reducer.js
  src/ducks/selectors.js
  src/ducks/utils.js
Labels: enhancement

#197 eslint
  .editorconfig
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/components/Battle.js
  src/components/Card.js
  src/components/CardLibrary.js
  src/components/DeckPile.js
  src/components/DiscardPile.js
  src/components/Game.js
  src/components/MapScreen.js
  src/components/Monster.js
  src/components/MonsterLibrary.js
  src/components/PercentileBar.js
  src/components/PortalScreen.js
  src/components/RewardScreen.js
  src/components/Sprites.js
  src/components/StartScreen.js
  src/components/styles/BattleStyle.js
  src/configureStore.js
  src/ducks/actionCreators.js
  src/ducks/actionTypes.js
  src/ducks/middlewares.js
  src/ducks/reducer.js
  src/ducks/selectors.js
  src/ducks/utils.js
  src/index.js
Labels: enhancement

#200 Fixes targeted attacks not working
  src/ducks/middlewares.js
Labels: bug
